# Generated by Django 3.1.3 on 2020-12-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0002_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specilization',
            new_name='specilizatio',
        ),
    ]
