# Generated by Django 3.1.3 on 2020-12-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0005_auto_20201209_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specilization',
            new_name='spc',
        ),
    ]
