# Generated by Django 3.1.3 on 2020-12-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0006_auto_20201209_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='spc',
            new_name='speciliation',
        ),
    ]
