# Generated by Django 3.1.3 on 2020-12-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0007_auto_20201209_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='speciliation',
            new_name='spc',
        ),
    ]
