# Generated by Django 3.1.3 on 2021-01-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0008_auto_20201209_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='patinet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
