# Generated by Django 3.1.3 on 2021-01-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0009_patinet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patinet',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
