# Generated by Django 3.1.3 on 2021-01-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0013_auto_20210116_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patinet',
            name='height',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patinet',
            name='weight',
            field=models.CharField(max_length=50),
        ),
    ]
