# Generated by Django 3.1.3 on 2021-01-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0014_auto_20210117_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profile'),
        ),
    ]
