# Generated by Django 3.1.3 on 2021-03-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0015_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_email', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('appointment_slot', models.CharField(max_length=1)),
                ('monday', models.CharField(default='', max_length=30)),
                ('tuesday', models.CharField(default='', max_length=30)),
                ('wednesday', models.CharField(default='', max_length=30)),
                ('thursday', models.CharField(default='', max_length=30)),
                ('friday', models.CharField(default='', max_length=30)),
                ('saturday', models.CharField(default='', max_length=30)),
                ('sunday', models.CharField(default='', max_length=30)),
                ('start_time', models.CharField(default='', max_length=30)),
                ('end_time', models.CharField(default='', max_length=30)),
                ('availability', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
