# Generated by Django 3.1.3 on 2021-04-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0016_doctor_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='patinet',
            name='appointment_link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
