# Generated by Django 3.1.3 on 2021-04-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0017_patinet_appointment_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients_asspointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_email', models.CharField(default='', max_length=30)),
                ('doctor_email', models.CharField(default='', max_length=30)),
                ('appointment_status', models.CharField(default='', max_length=30)),
                ('booking_date', models.DateField(default='')),
                ('appointment_day', models.CharField(default='', max_length=30)),
                ('amount', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
