# Generated by Django 3.1.3 on 2021-04-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0018_patients_asspointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients_asspointment',
            name='doctor_first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patients_asspointment',
            name='doctor_last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
