# Generated by Django 3.1.3 on 2021-04-27 17:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0020_patients_asspointment_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients_asspointment',
            name='patient_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patients_asspointment',
            name='patient_contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='patients_asspointment',
            name='patient_first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patients_asspointment',
            name='patient_last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patients_asspointment',
            name='patient_province',
            field=models.CharField(default='', max_length=50),
        ),
    ]
