# Generated by Django 3.1.3 on 2021-05-01 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0021_auto_20210427_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients_asspointment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
