# Generated by Django 3.1.3 on 2021-05-08 09:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0025_auto_20210502_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_email', models.CharField(default='', max_length=30)),
                ('patient_first_name', models.CharField(default='', max_length=30)),
                ('patient_last_name', models.CharField(default='', max_length=30)),
                ('patient_city', models.CharField(default='', max_length=50)),
                ('patient_province', models.CharField(default='', max_length=50)),
                ('patient_contact_no', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('doctor_email', models.CharField(default='', max_length=30)),
                ('booking_date', models.DateTimeField(default='')),
                ('appointment_day', models.CharField(default='', max_length=30)),
                ('doctor_first_name', models.CharField(default='', max_length=30)),
                ('doctor_last_name', models.CharField(default='', max_length=30)),
                ('appointment_time', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=30)),
                ('doctor_image', models.ImageField(blank=True, null=True, upload_to='appointment_doctor_profile')),
                ('medicine', models.CharField(default='', max_length=30)),
                ('time', models.CharField(default='', max_length=30)),
                ('disease', models.CharField(default='', max_length=30)),
                ('quantity', models.CharField(default='', max_length=30)),
                ('days', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
