# Generated by Django 3.1.3 on 2021-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0026_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor_image',
            field=models.ImageField(blank=True, null=True, upload_to='pription'),
        ),
    ]
