# Generated by Django 3.1.3 on 2021-05-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0027_auto_20210508_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='time',
            field=models.CharField(default='', max_length=60),
        ),
    ]
