# Generated by Django 3.1.3 on 2021-05-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0028_auto_20210509_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
