# Generated by Django 3.1.3 on 2021-05-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0029_prescription_prescription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients_asspointment',
            name='prescription_date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
