# Generated by Django 3.1.3 on 2021-05-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedoctor', '0030_patients_asspointment_prescription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
